
import { Translation } from './types';

export const TRANSLATIONS: Record<'en' | 'bn', Translation> = {
  en: {
    dashboard: "Dashboard",
    students: "Students",
    attendance: "Attendance",
    results: "Results",
    addStudent: "Add Student",
    studentName: "Student Name (English)",
    rollNo: "Roll No.",
    class: "Class",
    section: "Section",
    gender: "Gender",
    actions: "Actions",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    statsTotalStudents: "Total Students",
    statsPresentToday: "Present Today",
    statsMale: "Students (Male)",
    statsFemale: "Students (Female)",
    aiInsights: "AI Insights",
    askAi: "AI Analysis",
    schoolName: "Nagarganj Dakhil Madrasha",
    madrasaOption: "Madrasa",
    schoolOption: "School",
    institutionType: "Institution",
    grade: "Grade",
    contact: "Phone Number",
    login: "Login",
    register: "Register",
    fullName: "Full Name",
    mobileNumber: "Mobile",
    email: "Email",
    emailOrMobile: "Email or Mobile",
    password: "Password",
    logout: "Logout",
    noAccount: "No account? Register",
    haveAccount: "Already have an account? Login",
    welcomeBack: "Welcome",
    createNewAccount: "Create Admin Account",
  },
  bn: {
    dashboard: "ড্যাশবোর্ড",
    students: "শিক্ষার্থী",
    attendance: "উপস্থিতি",
    results: "ফলাফল",
    addStudent: "নতুন শিক্ষার্থী",
    studentName: "শিক্ষার্থীর নাম (ইংরেজি)",
    rollNo: "রোল নম্বর",
    class: "শ্রেণী",
    section: "শাখা",
    gender: "লিঙ্গ",
    actions: "কাজ",
    save: "সংরক্ষণ",
    cancel: "বাতিল",
    edit: "সম্পাদনা",
    delete: "মুছে ফেলুন",
    statsTotalStudents: "মোট শিক্ষার্থী",
    statsPresentToday: "আজকের উপস্থিতি",
    statsMale: "ছাত্র",
    statsFemale: "ছাত্রী",
    aiInsights: "এআই রিপোর্ট",
    askAi: "এআই বিশ্লেষণ",
    schoolName: "নাগরগঞ্জ দাখিল মাদ্রাসা",
    madrasaOption: "মাদ্রাসা",
    schoolOption: "স্কুল",
    institutionType: "প্রতিষ্ঠান",
    grade: "গ্রেড",
    contact: "মোবাইল নম্বর",
    login: "লগইন",
    register: "রেজিস্ট্রেশন",
    fullName: "পূর্ণ নাম",
    mobileNumber: "মোবাইল নম্বর",
    email: "ইমেইল",
    emailOrMobile: "ইমেইল অথবা মোবাইল",
    password: "পাসওয়ার্ড",
    logout: "লগ আউট",
    noAccount: "অ্যাকাউন্ট নেই? রেজিস্ট্রেশন",
    haveAccount: "অ্যাকাউন্ট আছে? লগইন",
    welcomeBack: "স্বাগতম",
    createNewAccount: "নতুন অ্যাকাউন্ট",
  }
};

export const CLASSES_MADRASA = [
  'Ibtidai 1', 'Ibtidai 2', 'Ibtidai 3', 'Ibtidai 4', 'Ibtidai 5', 
  'Dakhil 6', 'Dakhil 7', 'Dakhil 8', 'Dakhil 9', 'Dakhil 10', 
  'Alim 1st Year', 'Alim 2nd Year'
];
